/**
 * This file is auto-generated by scripts/directory-config.mjs.
 * Do not edit manually.
 */
export const defaultDirectoryUi = {
  "theme": {
    "primary": "#F97316",
    "accent": "#FBBF24",
    "background": "#FFF8E7"
  },
  "copy": {
    "appTitle": "FuzzPuppy Pack Finder",
    "listTitle": "Dog-Friendly Highlights",
    "listSubtitle": "Sniff out the best spots for pups and their humans.",
    "emptyState": "No dog-friendly spots yet—keep those tails wagging and try again soon.",
    "inspectorLocationLabel": "Pup Patrol HQ",
    "filterLabel": "Filter by Fetch",
    "detailFallback": "Discover tail-wagging adventures curated for your pack.",
    "reviewsTitle": "Pack Notes",
    "learnMoreLabel": "Fetch details"
  },
  "branding": {
    "logoUrl": "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=240&q=80"
  },
  "fields": {
    "title": "name",
    "subtitle": "neighborhood",
    "description": "description",
    "rating": "rating",
    "price": "price",
    "thumbnail": "thumbnail",
    "address": "address",
    "city": "city",
    "region": "region",
    "neighborhood": "neighborhood"
  },
  "map": {
    "latitudeField": "coords.1",
    "longitudeField": "coords.0",
    "defaultZoom": 12
  },
  "filters": {
    "locationFields": [
      "city",
      "neighborhood"
    ],
    "priceField": "price",
    "ratingField": "rating"
  }
};

export const defaultStructuredContent = {
  "resultsTitle": "Dog-Friendly Highlights",
  "items": [
    {
      "id": "golden-gate-bark",
      "name": "Golden Gate Barklands",
      "description": "Off-leash meadows tucked beneath the cypress trees with dog fountains and agility logs.",
      "address": "Transverse Dr & Middle Dr W",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Golden Gate Park",
      "rating": 4.9,
      "price": "$",
      "coords": [
        -122.4862,
        37.7694
      ],
      "thumbnail": "https://images.unsplash.com/photo-1525253086316-d0c936c814f8?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "mission-mutt-market",
      "name": "Mission Mutt Market",
      "description": "Dog-forward cafe pairing single-origin espresso with pup cups, bully stick flights, and toy swaps.",
      "address": "700 Valencia St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Mission District",
      "rating": 4.8,
      "price": "$$",
      "coords": [
        -122.4195,
        37.761
      ],
      "thumbnail": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "bay-fetch-beach",
      "name": "Bay Fetch Beach",
      "description": "Wind-sheltered stretch of Crissy Field where pups chase tennis balls into the bay at golden hour.",
      "address": "Crissy Field East Beach",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Presidio",
      "rating": 4.7,
      "price": "$",
      "coords": [
        -122.4642,
        37.8043
      ],
      "thumbnail": "https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "paws-and-pours",
      "name": "Paws & Pours Taproom",
      "description": "Small-batch brewery with a fenced sniff patio, dog beer flights, and weekend adoption pop-ups.",
      "address": "250 Townsend St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "SoMa",
      "rating": 4.6,
      "price": "$$",
      "coords": [
        -122.398,
        37.7765
      ],
      "thumbnail": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "whisker-wash-spa",
      "name": "Whisker Wash Spa",
      "description": "Spa-style grooming studio featuring hypoallergenic soaks, blueberry facials, and paw balm bar.",
      "address": "3200 Polk St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Marina District",
      "rating": 4.5,
      "price": "$$",
      "coords": [
        -122.422,
        37.8007
      ],
      "thumbnail": "https://images.unsplash.com/photo-1560807707-8cc77767d783?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "treat-truck-stop",
      "name": "Treat Truck Stop",
      "description": "Rotating lineup of gourmet pup treat trucks with chews, frozen paw-sicles, and training demos.",
      "address": "Pier 7",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Embarcadero",
      "rating": 4.6,
      "price": "$",
      "coords": [
        -122.3919,
        37.7989
      ],
      "thumbnail": "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "sniffari-trails",
      "name": "Sniffari Trails",
      "description": "Shaded canyon paths with scent stations, paw-friendly creek crossings, and weekend pack hikes.",
      "address": "200 Elk St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Glen Canyon",
      "rating": 4.7,
      "price": "$",
      "coords": [
        -122.4464,
        37.7385
      ],
      "thumbnail": "https://images.unsplash.com/photo-1433162653888-a571db5ccccf?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "barketplace-collective",
      "name": "Barketplace Collective",
      "description": "Hayes Valley concept shop with artisan leashes, local kibble makers, and on-call pup stylists.",
      "address": "432 Octavia St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Hayes Valley",
      "rating": 4.6,
      "price": "$$",
      "coords": [
        -122.425,
        37.776
      ],
      "thumbnail": "https://images.unsplash.com/photo-1494256997604-768d1f608cac?auto=format&fit=crop&w=400&q=80"
    }
  ],
  "ui": {
    "theme": {
      "primary": "#F97316",
      "accent": "#FBBF24",
      "background": "#FFF8E7"
    },
    "copy": {
      "appTitle": "FuzzPuppy Pack Finder",
      "listTitle": "Dog-Friendly Highlights",
      "listSubtitle": "Sniff out the best spots for pups and their humans.",
      "emptyState": "No dog-friendly spots yet—keep those tails wagging and try again soon.",
      "inspectorLocationLabel": "Pup Patrol HQ",
      "filterLabel": "Filter by Fetch",
      "detailFallback": "Discover tail-wagging adventures curated for your pack.",
      "reviewsTitle": "Pack Notes",
      "learnMoreLabel": "Fetch details"
    },
    "branding": {
      "logoUrl": "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=240&q=80"
    },
    "fields": {
      "title": "name",
      "subtitle": "neighborhood",
      "description": "description",
      "rating": "rating",
      "price": "price",
      "thumbnail": "thumbnail",
      "address": "address",
      "city": "city",
      "region": "region",
      "neighborhood": "neighborhood"
    },
    "map": {
      "latitudeField": "coords.1",
      "longitudeField": "coords.0",
      "defaultZoom": 12
    },
    "filters": {
      "locationFields": [
        "city",
        "neighborhood"
      ],
      "priceField": "price",
      "ratingField": "rating"
    }
  },
  "directory": {
    "label": "FuzzPuppy Dog Directory",
    "slug": "fuzzpuppy-directory"
  }
};
