/**
 * This file is auto-generated by scripts/directory-config.mjs.
 * Do not edit manually.
 */
export const defaultDirectoryUi = {
  "theme": {
    "primary": "#2563EB",
    "accent": "#10B981",
    "background": "#F8FAFC"
  },
  "copy": {
    "appTitle": "Directory Demo",
    "listTitle": "City Highlights",
    "listSubtitle": "A shortlist of places locals love",
    "emptyState": "No places match yet.",
    "inspectorLocationLabel": "San Francisco Bay Area",
    "filterLabel": "Filter",
    "detailFallback": "Explore the neighborhood highlights curated for your day.",
    "reviewsTitle": "Visitor notes",
    "learnMoreLabel": "Learn more"
  },
  "branding": {
    "logoUrl": "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=180&q=80"
  },
  "fields": {
    "title": "name",
    "subtitle": "neighborhood",
    "description": "description",
    "rating": "rating",
    "price": "price",
    "thumbnail": "thumbnail",
    "address": "address",
    "city": "city",
    "region": "region",
    "neighborhood": "neighborhood"
  },
  "map": {
    "latitudeField": "coords.1",
    "longitudeField": "coords.0",
    "defaultZoom": 12
  },
  "filters": {
    "locationFields": [
      "city",
      "neighborhood"
    ],
    "priceField": "price",
    "ratingField": "rating"
  }
};

export const defaultStructuredContent = {
  "resultsTitle": "City Highlights",
  "items": [
    {
      "id": "harbor-and-pine",
      "name": "Seaport & Clouds Coffeehouse",
      "description": "Sunlit cafe with rotating micro-roasters and roomy communal tables.",
      "address": "415 Harbor Ave",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "North Beach",
      "rating": 4.8,
      "price": "$$",
      "coords": [
        -122.4105,
        37.8008
      ],
      "thumbnail": "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "gallery-mercantile",
      "name": "Gallery Mercantile",
      "description": "Indie art gallery with local makers and Friday salon nights.",
      "address": "90 Montgomery St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Jackson Square",
      "rating": 4.7,
      "price": "$$",
      "coords": [
        -122.4028,
        37.7973
      ],
      "thumbnail": "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "skyline-lookout",
      "name": "Skyline Lookout Terrace",
      "description": "Glass rooftop lounge with 360° views and seasonal mocktails.",
      "address": "1 Market St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Downtown",
      "rating": 4.6,
      "price": "$$$",
      "coords": [
        -122.4012,
        37.7915
      ],
      "thumbnail": "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "maker-lane-studio",
      "name": "Maker Lane Studio",
      "description": "Hands-on workshop for ceramics, textiles, and screen printing.",
      "address": "245 Maker Ln",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "SoMa",
      "rating": 4.5,
      "price": "$$",
      "coords": [
        -122.4065,
        37.7802
      ],
      "thumbnail": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "bay-trail-commons",
      "name": "Bay Trail Commons",
      "description": "Waterfront park with pop-up markets and weekend yoga.",
      "address": "100 Pier 7",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Embarcadero",
      "rating": 4.6,
      "price": "$",
      "coords": [
        -122.3919,
        37.7989
      ],
      "thumbnail": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "lumen-reading-room",
      "name": "Lumen Reading Room",
      "description": "Quiet library lounge with floor-to-ceiling stacks and tea service.",
      "address": "1919 Pacific Ave",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Pacific Heights",
      "rating": 4.7,
      "price": "$$",
      "coords": [
        -122.4362,
        37.7924
      ],
      "thumbnail": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "evening-market-arcade",
      "name": "Evening Market Arcade",
      "description": "Late-night food hall featuring small batch vendors and live sets.",
      "address": "700 Valencia St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Mission District",
      "rating": 4.5,
      "price": "$$",
      "coords": [
        -122.4192,
        37.7603
      ],
      "thumbnail": "https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=400&q=80"
    },
    {
      "id": "sunset-conservatory",
      "name": "Sunset Conservatory",
      "description": "Greenhouse-inspired workspace filled with greenery and natural light.",
      "address": "1234 Judah St",
      "city": "San Francisco",
      "region": "CA",
      "neighborhood": "Sunset",
      "rating": 4.4,
      "price": "$$",
      "coords": [
        -122.4855,
        37.7593
      ],
      "thumbnail": "https://images.unsplash.com/photo-1523419409543-0c1df022bdd5?auto=format&fit=crop&w=400&q=80"
    }
  ],
  "ui": {
    "theme": {
      "primary": "#2563EB",
      "accent": "#10B981",
      "background": "#F8FAFC"
    },
    "copy": {
      "appTitle": "Directory Demo",
      "listTitle": "City Highlights",
      "listSubtitle": "A shortlist of places locals love",
      "emptyState": "No places match yet.",
      "inspectorLocationLabel": "San Francisco Bay Area",
      "filterLabel": "Filter",
      "detailFallback": "Explore the neighborhood highlights curated for your day.",
      "reviewsTitle": "Visitor notes",
      "learnMoreLabel": "Learn more"
    },
    "branding": {
      "logoUrl": "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=180&q=80"
    },
    "fields": {
      "title": "name",
      "subtitle": "neighborhood",
      "description": "description",
      "rating": "rating",
      "price": "price",
      "thumbnail": "thumbnail",
      "address": "address",
      "city": "city",
      "region": "region",
      "neighborhood": "neighborhood"
    },
    "map": {
      "latitudeField": "coords.1",
      "longitudeField": "coords.0",
      "defaultZoom": 12
    },
    "filters": {
      "locationFields": [
        "city",
        "neighborhood"
      ],
      "priceField": "price",
      "ratingField": "rating"
    }
  },
  "directory": {
    "label": "OpenAI Apps Directory",
    "slug": "open-directory"
  }
};
